import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";
import { CategoryProvider } from "./(context)/CategoryContext";
import { NotificationProvider } from "./common/NotificationManager";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CategoryProvider>
          <NotificationProvider maxVisible={3} position="bottom-right">
            <DashboardWrapper>{children}</DashboardWrapper>
          </NotificationProvider>
        </CategoryProvider>
      </body>
    </html>
  );
}