import type { Metadata } from "next";
import { Inter, Roboto, Open_Sans, Nunito } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";
import { CategoryProvider } from "./(context)/CategoryContext";
import { NotificationProvider } from "./common/NotificationManager";

// Configure multiple professional fonts
const inter = Inter({ 
  subsets: ["latin"], 
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'] 
});

const roboto = Roboto({ 
  subsets: ["latin"], 
  variable: '--font-roboto',
  weight: ['400', '500', '700'] 
});

const openSans = Open_Sans({ 
  subsets: ["latin"], 
  variable: '--font-open-sans',
  weight: ['400', '600', '700'] 
});

const nunito = Nunito({ 
  subsets: ["latin"], 
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700'] 
});

export const metadata: Metadata = {
  title: "Create An Inventory and Sales Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.variable} ${roboto.variable} ${openSans.variable} ${nunito.variable}`}>
        <CategoryProvider>
          <NotificationProvider maxVisible={3} position="bottom-right">
            <DashboardWrapper>{children}</DashboardWrapper>
          </NotificationProvider>
        </CategoryProvider>
      </body>
    </html>
  );
}